from enum import StrEnum


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(StrEnum):
    OPEN = "OPEN"
    ANALYZING = "ANALYZING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"
    CLOSED = "CLOSED"


class Category(StrEnum):
    SECURITY = "SECURITY"
    PERFORMANCE = "PERFORMANCE"
    DATABASE = "DATABASE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    APPLICATION = "APPLICATION"
    NETWORK = "NETWORK"
    OTHER = "OTHER"


class ActionStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class ActionType(StrEnum):
    RESTART_SERVICE = "RESTART_SERVICE"
    CLEAR_CACHE = "CLEAR_CACHE"
    SCALE_SERVICE = "SCALE_SERVICE"
    DISABLE_FEATURE = "DISABLE_FEATURE"
    RUN_HEALTH_CHECK = "RUN_HEALTH_CHECK"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"
    CUSTOM = "CUSTOM"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"